// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDKId6saDKYCzJfCq7M6GMbOcRukm-t0TI',
    appId: '1:136407293489:web:f6a2d2c83f2a87782a7f10',
    messagingSenderId: '136407293489',
    projectId: 'aula01-firebase-f4719',
    authDomain: 'aula01-firebase-f4719.firebaseapp.com',
    databaseURL: 'https://aula01-firebase-f4719-default-rtdb.firebaseio.com',
    storageBucket: 'aula01-firebase-f4719.firebasestorage.app',
    measurementId: 'G-NY71793MB2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA71ULZ6QdYKTri6B0aKqU5KTAT94FTmqg',
    appId: '1:136407293489:android:b9158348bcee8ac12a7f10',
    messagingSenderId: '136407293489',
    projectId: 'aula01-firebase-f4719',
    databaseURL: 'https://aula01-firebase-f4719-default-rtdb.firebaseio.com',
    storageBucket: 'aula01-firebase-f4719.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf-aCFe_3oFfNwiJNCzraDckGy-zripHE',
    appId: '1:136407293489:ios:74c26e919cd59b652a7f10',
    messagingSenderId: '136407293489',
    projectId: 'aula01-firebase-f4719',
    databaseURL: 'https://aula01-firebase-f4719-default-rtdb.firebaseio.com',
    storageBucket: 'aula01-firebase-f4719.firebasestorage.app',
    iosBundleId: 'com.example.atividade4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf-aCFe_3oFfNwiJNCzraDckGy-zripHE',
    appId: '1:136407293489:ios:74c26e919cd59b652a7f10',
    messagingSenderId: '136407293489',
    projectId: 'aula01-firebase-f4719',
    databaseURL: 'https://aula01-firebase-f4719-default-rtdb.firebaseio.com',
    storageBucket: 'aula01-firebase-f4719.firebasestorage.app',
    iosBundleId: 'com.example.atividade4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKId6saDKYCzJfCq7M6GMbOcRukm-t0TI',
    appId: '1:136407293489:web:20e78028e2fce4dc2a7f10',
    messagingSenderId: '136407293489',
    projectId: 'aula01-firebase-f4719',
    authDomain: 'aula01-firebase-f4719.firebaseapp.com',
    databaseURL: 'https://aula01-firebase-f4719-default-rtdb.firebaseio.com',
    storageBucket: 'aula01-firebase-f4719.firebasestorage.app',
    measurementId: 'G-KPXT5RTPHL',
  );
}
